name: Build
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
      - name: CreateJar
        run: ./gradlew createreobfPaperclipJar
      - name: artifact
        uses: actions/upload-artifact@v3
        with: 
          name: "Jar"
          path: |
            build/slimeworldmanager-paperclip-1.19.4-R0.1-SNAPSHOT-reobf.jar
